services:
  bootcamp-app:
    build: .
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/workspace
    environment:
      BOOTCAMP_HOST: 0.0.0.0
      BOOTCAMP_PORT: 8000
    command: python -m app.app
